import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/app/components/AuthSessionProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { Grid } from "@mui/material";
import TopNavBar from "./components/TopNavBar";
import SideNavBar from "./components/SIdeNavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  if (!session) {
    redirect("/auth/login");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider session={session}>
          <TopNavBar />
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
